name: sentry
version: 7.9.0
description: >
  A crash reporting library for Dart that sends crash reports to Sentry.io.
  This library supports Dart VM and Web. For Flutter consider sentry_flutter instead.
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=1.1.0 <2.0.0'
  meta: ^1.9.1
  stack_trace: ^1.11.0
  uuid: ^4.0.0

dev_dependencies:
  mockito: ^5.4.2
  lints: ^2.1.1
  test: ^1.21.1
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  collection: ^1.16.0
  coverage: ^1.6.3
  intl: '>=0.17.0 <1.0.0'
