name: sentry_flutter_example
description: Demonstrates how to use the sentry_flutter plugin.
version: 7.9.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  sentry:
  sentry_flutter:
  sentry_dio:
  sentry_logging:
  sentry_sqflite:
  sentry_file:
  universal_platform: ^1.0.0+1
  feedback: ^3.0.1
  provider: ^6.1.2
  dio: any # This gets constrained by `sentry_dio`
  sqflite: any # This gets constrained by `sentry_sqflite`
  logging: any # This gets constrained by `sentry_logging`
  package_info_plus:
    git: https://github.com/kumsumit/package_info_plus.git
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  #sqflite_common_ffi: ^2.0.0
  #sqflite_common_ffi_web: ^0.3.0
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  sentry_dart_plugin: ^1.7.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lorem-ipsum.txt
    - assets/sentry-wordmark.png

sentry:
  upload_source_maps: true
  upload_sources: true
  project: sentry-flutter
  org: sentry-sdks
  wait_for_processing: true
  commits: true
  ignore_missing: true
  log_level: info
