name: sentry_logging
description: An integration which adds support for recording log from the logging package.
version: 7.9.0
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/logging/

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  logging: ^1.2.0
  sentry: 7.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  yaml: ^3.1.2 # needed for version match (code and pubspec)
  coverage: ^1.7.2
  meta: ^1.11.0
