name: sentry_flutter
version: 7.9.0
description: Sentry SDK for Flutter. This package aims to support different Flutter targets by relying on the many platforms supported by Sentry with native SDKs.
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/flutter/

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sentry:
    git: https://github.com/kumsumit/sentry.git
  package_info_plus:
    git: https://github.com/kumsumit/package_info_plus.git
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  flutter_lints: ^3.0.0
  collection: ^1.18.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: SentryFlutterPlugin
        package: io.sentry.flutter
      ios:
        pluginClass: SentryFlutterPlugin
      macos:
        pluginClass: SentryFlutterPlugin
      web:
        pluginClass: SentryFlutterWeb
        fileName: sentry_flutter_web.dart
      linux:
        pluginClass: SentryFlutterPlugin
      windows:
        pluginClass: SentryFlutterPlugin
